// <auto-generated />
using System;
using ContosoDashboard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContosoDashboard.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260612021234_AddDocumentEntities")]
    partial class AddDocumentEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContosoDashboard.Models.Announcement", b =>
                {
                    b.Property<int>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnnouncementId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("AnnouncementId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Announcements");

                    b.HasData(
                        new
                        {
                            AnnouncementId = 1,
                            Content = "Welcome to the new ContosoDashboard application. This platform will help you manage your tasks and projects more efficiently.",
                            CreatedByUserId = 1,
                            ExpiryDate = new DateTime(2026, 7, 12, 2, 12, 34, 333, DateTimeKind.Utc).AddTicks(8310),
                            IsActive = true,
                            PublishDate = new DateTime(2026, 6, 12, 2, 12, 34, 333, DateTimeKind.Utc).AddTicks(8310),
                            Title = "Welcome to ContosoDashboard"
                        });
                });

            modelBuilder.Entity("ContosoDashboard.Models.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("StoredFilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("VersionNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("DocumentId");

                    b.HasIndex("Category");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StoredFilePath")
                        .IsUnique();

                    b.HasIndex("TaskId");

                    b.HasIndex("UploadedAt");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("ContosoDashboard.Models.DocumentShare", b =>
                {
                    b.Property<int>("DocumentShareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentShareId"));

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SharedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SharedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("SharedWithUserId")
                        .HasColumnType("int");

                    b.HasKey("DocumentShareId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("SharedByUserId");

                    b.HasIndex("SharedWithUserId");

                    b.ToTable("DocumentShares");
                });

            modelBuilder.Entity("ContosoDashboard.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ContosoDashboard.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ProjectManagerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TargetCompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ProjectId");

                    b.HasIndex("ProjectManagerId");

                    b.HasIndex("Status");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            CreatedDate = new DateTime(2026, 5, 13, 2, 12, 34, 333, DateTimeKind.Utc).AddTicks(8250),
                            Description = "Internal employee productivity dashboard",
                            Name = "ContosoDashboard Development",
                            ProjectManagerId = 2,
                            StartDate = new DateTime(2026, 5, 13, 2, 12, 34, 333, DateTimeKind.Utc).AddTicks(8240),
                            Status = 1,
                            TargetCompletionDate = new DateTime(2026, 8, 11, 2, 12, 34, 333, DateTimeKind.Utc).AddTicks(8250),
                            UpdatedDate = new DateTime(2026, 6, 12, 2, 12, 34, 333, DateTimeKind.Utc).AddTicks(8250)
                        });
                });

            modelBuilder.Entity("ContosoDashboard.Models.ProjectMember", b =>
                {
                    b.Property<int>("ProjectMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectMemberId"));

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ProjectMemberId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectMembers");

                    b.HasData(
                        new
                        {
                            ProjectMemberId = 1,
                            AssignedDate = new DateTime(2026, 5, 13, 2, 12, 34, 333, DateTimeKind.Utc).AddTicks(8290),
                            ProjectId = 1,
                            Role = "TeamLead",
                            UserId = 3
                        },
                        new
                        {
                            ProjectMemberId = 2,
                            AssignedDate = new DateTime(2026, 5, 13, 2, 12, 34, 333, DateTimeKind.Utc).AddTicks(8290),
                            ProjectId = 1,
                            Role = "Developer",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("ContosoDashboard.Models.TaskComment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("TaskComments");
                });

            modelBuilder.Entity("ContosoDashboard.Models.TaskItem", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<int>("AssignedUserId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TaskId");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DueDate");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Status");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            AssignedUserId = 4,
                            CreatedByUserId = 2,
                            CreatedDate = new DateTime(2026, 5, 13, 2, 12, 34, 333, DateTimeKind.Utc).AddTicks(8270),
                            Description = "Create entity relationship diagram and database design",
                            DueDate = new DateTime(2026, 5, 23, 2, 12, 34, 333, DateTimeKind.Utc).AddTicks(8270),
                            Priority = 2,
                            ProjectId = 1,
                            Status = 2,
                            Title = "Design database schema",
                            UpdatedDate = new DateTime(2026, 5, 23, 2, 12, 34, 333, DateTimeKind.Utc).AddTicks(8270)
                        },
                        new
                        {
                            TaskId = 2,
                            AssignedUserId = 4,
                            CreatedByUserId = 2,
                            CreatedDate = new DateTime(2026, 5, 18, 2, 12, 34, 333, DateTimeKind.Utc).AddTicks(8270),
                            Description = "Set up Microsoft Entra ID authentication",
                            DueDate = new DateTime(2026, 6, 17, 2, 12, 34, 333, DateTimeKind.Utc).AddTicks(8270),
                            Priority = 3,
                            ProjectId = 1,
                            Status = 1,
                            Title = "Implement authentication",
                            UpdatedDate = new DateTime(2026, 6, 12, 2, 12, 34, 333, DateTimeKind.Utc).AddTicks(8270)
                        },
                        new
                        {
                            TaskId = 3,
                            AssignedUserId = 4,
                            CreatedByUserId = 2,
                            CreatedDate = new DateTime(2026, 5, 23, 2, 12, 34, 333, DateTimeKind.Utc).AddTicks(8270),
                            Description = "Design user interface mockups for all main pages",
                            DueDate = new DateTime(2026, 6, 22, 2, 12, 34, 333, DateTimeKind.Utc).AddTicks(8270),
                            Priority = 1,
                            ProjectId = 1,
                            Status = 0,
                            Title = "Create UI mockups",
                            UpdatedDate = new DateTime(2026, 5, 23, 2, 12, 34, 333, DateTimeKind.Utc).AddTicks(8270)
                        });
                });

            modelBuilder.Entity("ContosoDashboard.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("AvailabilityStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("EmailNotificationsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("InAppNotificationsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            AvailabilityStatus = 0,
                            CreatedDate = new DateTime(2026, 6, 12, 2, 12, 34, 333, DateTimeKind.Utc).AddTicks(8170),
                            Department = "IT",
                            DisplayName = "System Administrator",
                            Email = "admin@contoso.com",
                            EmailNotificationsEnabled = true,
                            InAppNotificationsEnabled = true,
                            JobTitle = "Administrator",
                            Role = 3
                        },
                        new
                        {
                            UserId = 2,
                            AvailabilityStatus = 0,
                            CreatedDate = new DateTime(2026, 6, 12, 2, 12, 34, 333, DateTimeKind.Utc).AddTicks(8170),
                            Department = "Engineering",
                            DisplayName = "Camille Nicole",
                            Email = "camille.nicole@contoso.com",
                            EmailNotificationsEnabled = true,
                            InAppNotificationsEnabled = true,
                            JobTitle = "Project Manager",
                            Role = 2
                        },
                        new
                        {
                            UserId = 3,
                            AvailabilityStatus = 0,
                            CreatedDate = new DateTime(2026, 6, 12, 2, 12, 34, 333, DateTimeKind.Utc).AddTicks(8180),
                            Department = "Engineering",
                            DisplayName = "Floris Kregel",
                            Email = "floris.kregel@contoso.com",
                            EmailNotificationsEnabled = true,
                            InAppNotificationsEnabled = true,
                            JobTitle = "Team Lead",
                            Role = 1
                        },
                        new
                        {
                            UserId = 4,
                            AvailabilityStatus = 0,
                            CreatedDate = new DateTime(2026, 6, 12, 2, 12, 34, 333, DateTimeKind.Utc).AddTicks(8180),
                            Department = "Engineering",
                            DisplayName = "Ni Kang",
                            Email = "ni.kang@contoso.com",
                            EmailNotificationsEnabled = true,
                            InAppNotificationsEnabled = true,
                            JobTitle = "Software Engineer",
                            Role = 0
                        });
                });

            modelBuilder.Entity("ContosoDashboard.Models.Announcement", b =>
                {
                    b.HasOne("ContosoDashboard.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("ContosoDashboard.Models.Document", b =>
                {
                    b.HasOne("ContosoDashboard.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ContosoDashboard.Models.TaskItem", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ContosoDashboard.Models.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Task");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("ContosoDashboard.Models.DocumentShare", b =>
                {
                    b.HasOne("ContosoDashboard.Models.Document", "Document")
                        .WithMany("DocumentShares")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContosoDashboard.Models.User", "SharedByUser")
                        .WithMany()
                        .HasForeignKey("SharedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ContosoDashboard.Models.User", "SharedWithUser")
                        .WithMany()
                        .HasForeignKey("SharedWithUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("SharedByUser");

                    b.Navigation("SharedWithUser");
                });

            modelBuilder.Entity("ContosoDashboard.Models.Notification", b =>
                {
                    b.HasOne("ContosoDashboard.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ContosoDashboard.Models.Project", b =>
                {
                    b.HasOne("ContosoDashboard.Models.User", "ProjectManager")
                        .WithMany("ManagedProjects")
                        .HasForeignKey("ProjectManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProjectManager");
                });

            modelBuilder.Entity("ContosoDashboard.Models.ProjectMember", b =>
                {
                    b.HasOne("ContosoDashboard.Models.Project", "Project")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContosoDashboard.Models.User", "User")
                        .WithMany("ProjectMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ContosoDashboard.Models.TaskComment", b =>
                {
                    b.HasOne("ContosoDashboard.Models.TaskItem", "Task")
                        .WithMany("Comments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContosoDashboard.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ContosoDashboard.Models.TaskItem", b =>
                {
                    b.HasOne("ContosoDashboard.Models.User", "AssignedUser")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ContosoDashboard.Models.User", "CreatedByUser")
                        .WithMany("CreatedTasks")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ContosoDashboard.Models.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId");

                    b.Navigation("AssignedUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ContosoDashboard.Models.Document", b =>
                {
                    b.Navigation("DocumentShares");
                });

            modelBuilder.Entity("ContosoDashboard.Models.Project", b =>
                {
                    b.Navigation("ProjectMembers");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("ContosoDashboard.Models.TaskItem", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("ContosoDashboard.Models.User", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("Comments");

                    b.Navigation("CreatedTasks");

                    b.Navigation("ManagedProjects");

                    b.Navigation("Notifications");

                    b.Navigation("ProjectMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
